name: PHPUnit Tests

on:
  push:
    branches: [ main, meryem ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, intl, bcmath, pdo, mysqli
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Fix phpunit.xml if needed
        run: |
          sed -i '/cacheDirectory/d' phpunit.xml || true
          sed -i '/<source>/,/<\/source>/d' phpunit.xml || true

      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit --testdox
