name: PHPUnit Tests

on:
  push:
    branches: [ main, meryem ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, intl, bcmath, pdo, mysqli

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Run PHPUnit
        run: ./vendor/bin/phpunit
